# Generated by Django 4.1.4 on 2023-01-07 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="paid")),
                ("first_name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="family_name"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="Phone_number"),
                ),
                ("address", models.CharField(max_length=700, verbose_name="address")),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_modified", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
        ),
    ]
