# Generated by Django 4.1.4 on 2023-01-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_order_notes_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.PositiveIntegerField(verbose_name="price"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="quantity"),
        ),
    ]
