# Generated by Django 4.1.4 on 2023-01-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_orderitem_price_alter_orderitem_quantity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "order", "verbose_name_plural": "orders"},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={"verbose_name_plural": "orderitems"},
        ),
    ]
