# Generated by Django 4.1.4 on 2023-01-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_options_alter_orderitem_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={"verbose_name": "orderitem", "verbose_name_plural": "orderitems"},
        ),
        migrations.AlterField(
            model_name="order",
            name="datetime_created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="order_datetime"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="datetime_modified",
            field=models.DateTimeField(auto_now=True, verbose_name="checkout_datetime"),
        ),
    ]
