# Generated by Django 4.1.4 on 2023-03-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0005_alter_orderitem_options_alter_order_datetime_created_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="zarinpal_authority",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
