# Generated by Django 4.1.4 on 2023-03-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_zarinpal_authority"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="zarinpal_data",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="zarinpal_ref_id",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
