# Generated by Django 4.1.4 on 2022-12-25 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0002_alter_product_active_alter_product_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="text")),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "stars",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Very Bad"),
                            ("2", "Bad"),
                            ("3", "Normal"),
                            ("4", "Good"),
                            ("5", "Perfect"),
                        ],
                        max_length=10,
                        verbose_name="stars",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_modified", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="products.product",
                        verbose_name="product",
                    ),
                ),
            ],
        ),
    ]
