# Generated by Django 4.1.4 on 2023-01-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_comment_options_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cover",
            field=models.ImageField(
                blank=True, upload_to="covers/products/", verbose_name="product image"
            ),
        ),
    ]
