# Generated by Django 4.1.4 on 2023-01-04 03:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="datetime_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
